# Generated by Django 3.0.6 on 2020-05-08 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st_pauls_school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.IntegerField(max_length=200, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.IntegerField(max_length=200, verbose_name='password'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=150, verbose_name='Titulo')),
                ('teacher_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Teacher')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['subject_name'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(max_length=150, verbose_name='Titulo')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Student')),
                ('subject_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Subject')),
                ('teacher_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Teacher')),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'ordering': ['score'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=150, verbose_name='Titulo')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Student')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Teacher')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['course_name'],
            },
        ),
    ]
