# Generated by Django 3.0.6 on 2020-05-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_pauls_school', '0003_auto_20200508_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(max_length=150, verbose_name='Score'),
        ),
    ]
