# Generated by Django 3.0.6 on 2020-05-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_pauls_school', '0005_auto_20200508_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(verbose_name='Score'),
        ),
    ]
