# Generated by Django 3.0.6 on 2020-05-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_pauls_school', '0006_auto_20200508_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='student_id',
            field=models.ManyToManyField(to='st_pauls_school.Student'),
        ),
    ]
