# Generated by Django 3.0.6 on 2020-05-08 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st_pauls_school', '0007_teacher_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='score',
            name='subject_id',
            field=models.ManyToManyField(to='st_pauls_school.Subject'),
        ),
        migrations.AlterField(
            model_name='score',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Teacher'),
        ),
    ]
