# Generated by Django 3.0.6 on 2020-05-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_pauls_school', '0008_auto_20200508_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_id',
            field=models.ManyToManyField(to='st_pauls_school.Teacher'),
        ),
        migrations.RemoveField(
            model_name='score',
            name='student_id',
        ),
        migrations.AddField(
            model_name='score',
            name='student_id',
            field=models.ManyToManyField(to='st_pauls_school.Student'),
        ),
    ]
