# Generated by Django 3.0.6 on 2020-05-09 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st_pauls_school', '0009_auto_20200509_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='teacher_id',
        ),
        migrations.AlterField(
            model_name='course',
            name='student_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Student'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Teacher'),
        ),
        migrations.RemoveField(
            model_name='score',
            name='student_id',
        ),
        migrations.AddField(
            model_name='score',
            name='student_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Student'),
        ),
        migrations.RemoveField(
            model_name='score',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='score',
            name='subject_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(default='', max_length=150, verbose_name='Subject Name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='student_id',
            field=models.ManyToManyField(default='', to='st_pauls_school.Student'),
        ),
    ]
