# Generated by Django 3.0.6 on 2020-05-09 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st_pauls_school', '0010_auto_20200509_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sudent_id',
            field=models.ManyToManyField(to='st_pauls_school.Student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Teacher'),
        ),
    ]
