# Generated by Django 3.0.6 on 2020-05-10 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st_pauls_school', '0011_auto_20200509_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['score_final'], 'verbose_name': 'Score', 'verbose_name_plural': 'Scores'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='score',
            name='score',
        ),
        migrations.RemoveField(
            model_name='score',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='score',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sudent_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='student_id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='course_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Course'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Subject'),
        ),
        migrations.CreateModel(
            name='StudentSubjectScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_subject_score', models.IntegerField(verbose_name='Score')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='score_final',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.StudentSubjectScore'),
            preserve_default=False,
        ),
    ]
