# Generated by Django 3.0.6 on 2020-05-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('st_pauls_school', '0012_auto_20200510_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubjectscore',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='studentsubjectscore',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject_id',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentSubjectScore',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
