# Generated by Django 3.0.6 on 2020-05-10 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st_pauls_school', '0013_auto_20200510_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Course')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['name'],
            },
        ),
    ]
