# Generated by Django 3.0.6 on 2020-05-10 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st_pauls_school', '0015_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Subject'),
            preserve_default=False,
        ),
    ]
