# Generated by Django 3.0.6 on 2020-05-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_pauls_school', '0016_teacher_subject_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['name'],
            },
        ),
    ]
