# Generated by Django 3.0.6 on 2020-05-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_pauls_school', '0019_subjectstudent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectstudent',
            old_name='score',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(through='st_pauls_school.SubjectStudent', to='st_pauls_school.Subject'),
        ),
    ]
