# Generated by Django 3.0.6 on 2020-05-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('st_pauls_school', '0020_auto_20200510_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectstudent',
            name='quantity',
        ),
    ]
