# Generated by Django 3.0.6 on 2020-05-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_pauls_school', '0021_remove_subjectstudent_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(verbose_name='Score')),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'ordering': ['score'],
            },
        ),
        migrations.AlterModelOptions(
            name='subjectstudent',
            options={'ordering': ['student_id'], 'verbose_name': 'SubjectStudent', 'verbose_name_plural': 'SubjectStudent'},
        ),
    ]
