# Generated by Django 3.0.6 on 2020-05-10 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st_pauls_school', '0022_auto_20200510_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectStudentScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Score')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_pauls_school.Subject')),
            ],
            options={
                'verbose_name': 'SubjectStudentScore',
                'verbose_name_plural': 'SubjectStudentScores',
                'ordering': ['student_id'],
            },
        ),
    ]
