# Generated by Django 3.0.6 on 2020-05-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_pauls_school', '0024_score_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.EmailField(max_length=200, verbose_name='password'),
        ),
    ]
